export class GameError extends Error {
  constructor(code, message, status = 400) {
    super(message);
    this.name = 'GameError';
    this.code = code;
    this.status = status;
  }
}

export const errorCodes = {
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  GAME_NOT_STARTED: 'GAME_NOT_STARTED',
  INVALID_ACTION: 'INVALID_ACTION',
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  NOT_HOST: 'NOT_HOST',
  INVALID_ROLE: 'INVALID_ROLE',
  DEAD_PLAYER: 'DEAD_PLAYER',
  NAME_TAKEN: 'NAME_TAKEN',
  INVALID_NAME: 'INVALID_NAME',
  INVALID_CODE: 'INVALID_CODE',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  RATE_LIMITED: 'RATE_LIMITED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  DUPLICATE_ACTION: 'DUPLICATE_ACTION',
  SPECTATOR_NOT_ALLOWED: 'SPECTATOR_NOT_ALLOWED',
  INVALID_SETTINGS: 'INVALID_SETTINGS',
  INVALID_PHASE: 'INVALID_PHASE'
};
